---
#Ansible Galaxy dependencies
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.netcommon
  - name: kubernetes.core
  - name: containers.podman
  - name: community.general
  - name: community.crypto
  - name: community.okd
  - name: community.vmware
  - name: community.libvirt
  - name: community.hashi_vault
