---
# Ansible Galaxy dependencies
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.netcommon
  - name: kubernetes.core
  - name: community.general
  - name: community.crypto
  - name: community.okd
  - name: community.libvirt
#  - name: community.hashi_vault
#  - name: community.vmware
#  - name: containers.podman
#  - name: oracle.oci
